version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: reimbursement-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: reimbursement_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: